CREATE OR REPLACE TABLE `usuarios` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`apelido` VARCHAR(16) NOT NULL,
	`hash_senha` TEXT(1024) NOT NULL,
	`link_avatar` TEXT(1024) NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `posts` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`autor_id` INTEGER NOT NULL,
	`titulo` VARCHAR(32) NOT NULL,
	`conteudo` TEXT(65535) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `comentarios` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`autor_id` INTEGER NOT NULL,
	`post_id` INTEGER NOT NULL,
	`conteudo` TEXT(65535) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `mensagens` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`autor_id` INTEGER NOT NULL,
	`mensagem` TEXT(65535) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL,
	PRIMARY KEY(`id`)
);

ALTER TABLE `posts`
ADD FOREIGN KEY(`autor_id`) REFERENCES `usuarios`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `usuarios`
ADD FOREIGN KEY(`id`) REFERENCES `comentarios`(`autor_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `posts`
ADD FOREIGN KEY(`id`) REFERENCES `comentarios`(`post_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `usuarios`
ADD FOREIGN KEY(`id`) REFERENCES `mensagens`(`autor_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;